### ISSUE TITLE
Support code navigation for #include paths

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/scip-clang#107]
Following this request from `sourcegraph/sourcegraph`: https://github.com/sourcegraph/sourcegraph/issues/21838

To re-summarize in languages like Java we can resolve hovers for imports, for example:
`repo:^github\.com/elastic/elasticsearch$@985a2fb file:^server/src/main/java/org/elasticsearch/index/codec/CodecService\.java`
([link](https://sourcegraph.com/github.com/elastic/elasticsearch@985a2fb9b74e72b9c91517f34d8712018ab0fb61/-/blob/server/src/main/java/org/elasticsearch/index/codec/CodecService.java?L13:26-13:32#tab=def))
![Screenshot 2023-03-06 at 11 34 22 AM](https://user-images.githubusercontent.com/13024338/223212456-595fb6b7-4665-45d0-89a8-677c4815a45b.png)

What is desired here is the same behavior for C `includes` for example:
`repo:^github\.com/tensorflow/tensorflow$ file:^tensorflow/core/graph/validate\.h`
([link](https://sourcegraph.com/github.com/tensorflow/tensorflow/-/blob/tensorflow/core/graph/validate.h?subtree=true))

Here a hover on `tensorflow/lite/core/c/common.h` would ideally allow a user to jump to `https://sourcegraph.com/github.com/tensorflow/tensorflow/-/blob/tensorflow/lite/core/c/common.h`

Include
![Screenshot 2023-03-06 at 11 41 27 AM](https://user-images.githubusercontent.com/13024338/223213831-d7b48889-255a-4280-b2df-1ea8d0cdab93.png)

File to jump to
![Screenshot 2023-03-06 at 11 42 13 AM](https://user-images.githubusercontent.com/13024338/223213895-a36f6ba3-93f3-47a0-833d-479e9598aeef.png)

**Comment by varungandhi-src** [comment]
Added support in https://github.com/sourcegraph/scip-clang/pull/166

Example: https://sourcegraph.com/github.com/ninja-build/ninja/-/blob/src/graph.h?L23:10-23:20#tab=references

The hover text is a little weird, I will fix that later.
