### ISSUE TITLE
ProjectRoot format

### ISSUE THREAD

**Issue by qaqland** [sourcegraph/scip-clang#473]
https://github.com/sourcegraph/scip-clang/blob/b7ecba1fe978d24b1ea83ddebaf22dcee71e48c5/indexer/Driver.cc#L1049

maybe it should be `file://<path>`, thus become compatible with "standard parsing" like go?

https://go.dev/play/p/nUzyrTnqeMX

reference:

https://github.com/sourcegraph/scip/issues/98

**Comment by varungandhi-src** [comment]
You're right, it should be `file://`

**Comment by varungandhi-src** [comment]
Opened PR here: https://github.com/sourcegraph/scip-clang/pull/474

**Comment by qaqland** [comment]
thx
