### ISSUE TITLE
Type resolution for variables / function arguments

### ISSUE THREAD

**Issue by levibus** [sourcegraph/scip-clang#478]
Hi, I would like to use scip to create normalized function names that contain their argument types. For example, the function
```
foo(int a, double b)
```
would look something like `foo_int_double`. I've tried looking at many different fields in the index.scip result (SymbolInformation.signature_documentation looked promising) but the fields I look at either don't contain relevant information or are blank. However, variable type resolution seems like something that could be found with scip. For instance, I'm thinking of when you hover over a variable in an IDE and it gives you the variable type or you hover over a function and it gives you the function declaration. How can I find the types of variables or function arguments in a scip file?

**Comment by varungandhi-src** [comment]
scip-clang currently only supports information for code navigation, which doesn't include type information.

We have a proposed extension to SCIP to add structured signatures: https://github.com/sourcegraph/scip/pull/231

If we were to add that to SCIP, then scip-clang could potentially record that information and it would be accessible from the generated index.

> I'm thinking of when you hover over a variable in an IDE and it gives you the variable type or you hover over a function and it gives you the function declaration.

This is currently only part of the documentation strings.

I'm closing this as out-of-scope for now, as structured signatures haven't been added to SCIP.
